#!/bin/bash
# detect-tool-traces.sh — D3: detect tool traces in working tree + commit messages.
# Output: pipe-separated lines "category|severity|location|match"
#   severity: auto-removable | review-needed | manual
# Exit 0 if no auto-removable findings; exit 1 if any auto-removable exist.
#
# Bash 3.2-clean: no assoc arrays, no mapfile, no ${v^^}, no <(), no <<<
set -u

ROOT="${1:-$PWD}"

# Temporary file for all findings (avoids subshell variable propagation issues)
FINDINGS=$(mktemp)
# Temporary file for file list (avoids word-splitting on paths with spaces)
FILE_TMP=""
# Temporary file for commit log (declared early so EXIT trap can clean it up on signal)
COMMIT_LOG=""
trap 'rm -f "$FINDINGS" "${FILE_TMP:-}" "${COMMIT_LOG:-}"' EXIT

# -----------------------------------------------------------------------
# Determine file list
# -----------------------------------------------------------------------
if git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  USE_GIT=1
else
  USE_GIT=0
fi

# -----------------------------------------------------------------------
# is_dependency_context FILE MATCH_TEXT
# Returns 0 if the match looks like a dependency name context (review-needed guard).
# A match is dependency context if:
#   - match text contains "claude-" followed by [a-z0-9-]
#   - AND file is a known dependency manifest / source import file
# -----------------------------------------------------------------------
is_dependency_context() {
  local file="$1"
  local match_text="$2"
  local basename_file
  basename_file=$(basename "$file")

  # Only applies when match looks like a package/dependency name
  echo "$match_text" | grep -Eq 'claude-[a-z0-9]'
  if [ $? -ne 0 ]; then
    return 1
  fi

  # Known dependency manifest files
  case "$basename_file" in
    package.json|package-lock.json|yarn.lock|requirements.txt|setup.py|Pipfile|Pipfile.lock|pyproject.toml)
      return 0
      ;;
  esac

  # requirements with suffix (e.g. requirements-dev.txt)
  echo "$basename_file" | grep -Eq '^requirements.*\.txt$'
  if [ $? -eq 0 ]; then
    return 0
  fi

  # Import/require lines in source files
  echo "$match_text" | grep -Eq '(import|require|from).*claude-'
  if [ $? -eq 0 ]; then
    return 0
  fi

  return 1
}

# -----------------------------------------------------------------------
# Scan working tree files
# -----------------------------------------------------------------------
FILE_TMP=$(mktemp)
if [ "$USE_GIT" = "1" ]; then
  git -C "$ROOT" ls-files 2>/dev/null | while read -r f; do
    printf '%s/%s\n' "$ROOT" "$f"
  done > "$FILE_TMP"
else
  find "$ROOT" -type f > "$FILE_TMP"
fi

while read -r FPATH; do
  # Skip if not a regular file
  [ -f "$FPATH" ] || continue

  # Skip binary files
  grep -Iq . "$FPATH" 2>/dev/null || continue

  # Compute relative path for display
  REL="${FPATH#$ROOT/}"

  # --- Pattern group 1: trailer / header markers ---
  grep -nE 'Co-Authored-By:.*Claude|Generated with.*Claude Code' "$FPATH" 2>/dev/null | \
  while read -r GLINE; do
    LNUM=$(echo "$GLINE" | sed 's/^\([0-9]*\):.*/\1/')
    MATCH=$(echo "$GLINE" | sed 's/^[0-9]*://')
    # Doc-mention guard: a trailer shown inside backticks (code span) or after a
    # standalone negation (No/NON/not) is documentation describing the convention,
    # not an actual trailer → review-needed, not auto-removable. (Pilot Devonthink_MCP.)
    TRAILER_SEV="auto-removable"
    if echo "$MATCH" | grep -Eq '`' || echo "$MATCH" | grep -Eqi '(^|[^[:alpha:]])(no|non|not)([^[:alpha:]]|$)'; then
      TRAILER_SEV="review-needed"
    fi
    printf 'trailer|%s|%s:%s|%s\n' "$TRAILER_SEV" "$REL" "$LNUM" "$MATCH" >> "$FINDINGS"
  done

  # --- Pattern group 1b: claude.ai session URL traces ---
  # Catches session/code links already written in files or history.
  # Complements attribution.sessionUrl (settings.json, CC 2.1.183) which prevents them
  # in future commits for web/Remote Control sessions — this retroactive check covers
  # CLI-local sessions and any URL already committed. ADR-0011 scope.
  grep -nE 'claude\.ai/(session|code)[/a-zA-Z0-9_?=&-]*' "$FPATH" 2>/dev/null | \
  while read -r GLINE; do
    LNUM=$(echo "$GLINE" | sed 's/^\([0-9]*\):.*/\1/')
    MATCH=$(echo "$GLINE" | sed 's/^[0-9]*://')
    printf 'trailer|auto-removable|%s:%s|%s\n' "$REL" "$LNUM" "$MATCH" >> "$FINDINGS"
  done

  # --- Pattern group 2: comment traces ---
  # Pattern: "(added|generated) by Claude" or "# generated by" etc.
  grep -nE '(added|generated) by Claude|# *generated by' "$FPATH" 2>/dev/null | \
  while read -r GLINE; do
    LNUM=$(echo "$GLINE" | sed 's/^\([0-9]*\):.*/\1/')
    MATCH=$(echo "$GLINE" | sed 's/^[0-9]*://')
    printf 'comment-trace|auto-removable|%s:%s|%s\n' "$REL" "$LNUM" "$MATCH" >> "$FINDINGS"
  done

  # --- Pattern group 3: string claude/AI + emoji decorative ---
  # Find lines matching \bclaude\b (case-insensitive)
  grep -nEi '\bclaude\b' "$FPATH" 2>/dev/null | \
  while read -r GLINE; do
    LNUM=$(echo "$GLINE" | sed 's/^\([0-9]*\):.*/\1/')
    MATCH=$(echo "$GLINE" | sed 's/^[0-9]*://')

    # Skip if already captured as a comment-trace (avoid duplicate)
    echo "$MATCH" | grep -Eq '(added|generated) by Claude|# *generated by'
    if [ $? -eq 0 ]; then
      continue
    fi

    # Skip if already captured as trailer
    echo "$MATCH" | grep -Eq 'Co-Authored-By:.*Claude|Generated with.*Claude Code'
    if [ $? -eq 0 ]; then
      continue
    fi

    # Check dependency context
    is_dependency_context "$FPATH" "$MATCH"
    if [ $? -eq 0 ]; then
      printf 'string|review-needed|%s:%s|%s\n' "$REL" "$LNUM" "$MATCH" >> "$FINDINGS"
    else
      # Only auto-removable if line carries a decorative/branding signal:
      # (a) branding phrase or emoji shortcode (combined grep), OR
      # (b) a real pictographic emoji from the 4-byte plane (U+1F300–U+1FAFF,
      #     UTF-8 lead bytes F0 9F). Typographic Unicode (— → § ≤ box-drawing,
      #     accented letters) is 2-3 byte C2/C3/E2 and is NOT treated as emoji.
      #     (Pilot Devonthink_MCP: "any non-ASCII byte" caused 54 false positives.)
      DECORATIVE=0
      echo "$MATCH" | grep -Eqi 'built with|powered by|made with|generated (with|by)|created (with|by)|:[a-z0-9_+-]+:'
      if [ $? -eq 0 ]; then
        DECORATIVE=1
      fi
      if [ "$DECORATIVE" = "0" ]; then
        printf '%s' "$MATCH" | LC_ALL=C grep -qF "$(printf '\360\237')"
        if [ $? -eq 0 ]; then
          DECORATIVE=1
        fi
      fi
      if [ "$DECORATIVE" = "1" ]; then
        printf 'string-emoji|auto-removable|%s:%s|%s\n' "$REL" "$LNUM" "$MATCH" >> "$FINDINGS"
      else
        printf 'string|review-needed|%s:%s|%s\n' "$REL" "$LNUM" "$MATCH" >> "$FINDINGS"
      fi
    fi
  done

  # --- Pattern group 4: file slop by name ---
  basename_f=$(basename "$FPATH")
  case "$basename_f" in
    scratch*|*-COPY*|*-COPY.*|notes.md|NOTES.md)
      printf 'slop|manual|%s|slop filename: %s\n' "$REL" "$basename_f" >> "$FINDINGS"
      ;;
  esac

done < "$FILE_TMP"

# -----------------------------------------------------------------------
# Scan commit messages (only if git repo)
# -----------------------------------------------------------------------
if [ "$USE_GIT" = "1" ]; then
  # Use a temp file for commit log to avoid subshell issues
  COMMIT_LOG=$(mktemp)
  git -C "$ROOT" log --format="%h %B" 2>/dev/null > "$COMMIT_LOG"

  CURRENT_SHA=""
  while read -r LOG_LINE; do
    # Lines starting with a short SHA (7-40 hex chars + space) mark new commits. git's %h
    # honors core.abbrev (auto by default, can exceed 7 well before a repo is large), so
    # the boundary must not require an exact 7-char match.
    MAYBE_SHA=$(echo "$LOG_LINE" | grep -Eo '^[0-9a-f]{7,40} ')
    if [ -n "$MAYBE_SHA" ]; then
      CURRENT_SHA=$(echo "$MAYBE_SHA" | tr -d ' ')
    fi

    echo "$LOG_LINE" | grep -Eq 'Co-Authored-By:.*Claude|Generated with.*Claude Code'
    if [ $? -eq 0 ]; then
      MATCH=$(echo "$LOG_LINE" | grep -Eo 'Co-Authored-By:.*Claude.*|Generated with.*Claude Code.*' | head -1)
      printf 'commit-trailer|auto-removable|%s|%s\n' "$CURRENT_SHA" "$MATCH" >> "$FINDINGS"
    fi

    echo "$LOG_LINE" | grep -Eq 'claude\.ai/(session|code)[/a-zA-Z0-9_?=&-]*'
    if [ $? -eq 0 ]; then
      MATCH=$(echo "$LOG_LINE" | grep -Eo 'claude\.ai/(session|code)[/a-zA-Z0-9_?=&-]*' | head -1)
      printf 'commit-trailer|auto-removable|%s|%s\n' "$CURRENT_SHA" "$MATCH" >> "$FINDINGS"
    fi
  done < "$COMMIT_LOG"
  # COMMIT_LOG cleanup handled by the EXIT trap (consistent with FILE_TMP/FINDINGS).
fi

# -----------------------------------------------------------------------
# Output findings
# -----------------------------------------------------------------------
if [ -f "$FINDINGS" ]; then
  cat "$FINDINGS"
fi

# -----------------------------------------------------------------------
# Exit code: 1 if any auto-removable findings
# -----------------------------------------------------------------------
if grep -q '|auto-removable|' "$FINDINGS" 2>/dev/null; then
  exit 1
fi
exit 0
